version: '3'
services:
  app:
    container_name: "mekki"
    build: .
    ports:
      - "6005:6005" # For development; SWANK port. cf. Dockerfile
    volumes:
      - ./:/app
      - cache:/root/.cache
      - slime_cache:/root/.slime
volumes:
  cache:
  slime_cache:
